package it.deltascientia.model;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.Instant;

/**
 * Stores the measured value of a {@link Variable} within a specific {@link Trial}.
 * Uses separate columns for different value types to enable efficient
 * numeric filtering and aggregation queries.
 */
@Entity
@Table(name = "trial_value")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class TrialValue {

    /** Unique identifier, auto-generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @EqualsAndHashCode.Include
    private Long id;

    /** The trial this value belongs to. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "trial_id", nullable = false)
    @ToString.Exclude
    private Trial trial;

    /** The variable being measured. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "variable_id", nullable = false)
    @ToString.Exclude
    private Variable variable;

    /** Textual value for qualitative or short string data. */
    @Column(name = "value_text", length = 4000)
    private String valueText;

    /** Numeric value for quantitative measurements, enables range queries. */
    @Column(name = "value_numeric")
    private Double valueNumeric;

    /** Long-form text value for extended observations or notes. */
    @Lob
    @Column(name = "value_long_text", columnDefinition = "TEXT")
    private String valueLongText;

    /** Timestamp of row creation, managed by Hibernate. */
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;
}
