package it.deltascientia.model;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;

/**
 * Represents a single trial run within an {@link Experiment}.
 * Each trial records values for the variables defined at the experiment level.
 */
@Entity
@Table(name = "trial")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class Trial {

    /** Unique identifier, auto-generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @EqualsAndHashCode.Include
    private Long id;

    /** The experiment this trial belongs to. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "experiment_id", nullable = false)
    @ToString.Exclude
    private Experiment experiment;

    /** Sequential number of the trial within the experiment. */
    @Column(name = "trial_number")
    private Integer trialNumber;

    /** Optional human-readable label for this trial. */
    @Column(length = 255)
    private String label;

    /** Free-form observations or notes about this trial. */
    @Lob
    @Column(columnDefinition = "TEXT")
    private String notes;

    /** Timestamp of when the trial was actually executed. */
    @Column(name = "execution_date")
    private Instant executionDate;

    /** Timestamp of row creation, managed by Hibernate. */
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Measured values for each variable in this trial. */
    @OneToMany(mappedBy = "trial", cascade = CascadeType.ALL, orphanRemoval = true)
    @Builder.Default
    private List<TrialValue> values = new ArrayList<>();
}
