package it.deltascientia.model;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;

/**
 * A catalog of standard variable types shared across experiments.
 * Enables cross-experiment comparison by establishing a common
 * vocabulary for measurements (e.g., "Temperature", "pH Level").
 * Custom variables defined by users are also persisted here
 * with the {@code isCustom} flag set to {@code true}.
 */
@Entity
@Table(name = "variable_type", uniqueConstraints = {
    @UniqueConstraint(name = "uk_variable_type_name", columnNames = "name")
})
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class VariableType {

    /** Unique identifier, auto-generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @EqualsAndHashCode.Include
    private Long id;

    /**
     * Human-readable type name (e.g. "Temperature", "pH Level").
     * Unique and case-insensitive at the application level.
     */
    @Column(nullable = false, length = 255, unique = true)
    private String name;

    /** Unit of measurement (e.g. "°C", "mol/L"). Null for non-numeric types. */
    @Column(name = "unit_of_measure", length = 100)
    private String unitOfMeasure;

    /** Declared data type (e.g. "NUMERIC", "TEXT"). */
    @Column(name = "data_type", length = 50, nullable = false)
    private String dataType;

    /** Brief description of what this variable measures. */
    @Column(length = 500)
    private String description;

    /**
     * {@code true} if this type was created by a user as a custom variable.
     * {@code false} if it belongs to the initial catalog.
     */
    @Column(name = "is_custom", nullable = false)
    @Builder.Default
    private Boolean isCustom = false;

    /** Timestamp of row creation, managed by Hibernate. */
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** Variables across experiments that reference this type. */
    @OneToMany(mappedBy = "variableType")
    @Builder.Default
    private List<Variable> variables = new ArrayList<>();
}
