package it.deltascientia.model;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;

/**
 * Links a {@link VariableType} to an {@link Experiment},
 * enabling measurements to be recorded via {@link TrialValue} rows.
 * All metadata (name, unit, data type, description) is derived from the type.
 */
@Entity
@Table(name = "variable")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class Variable {

    /** Unique identifier, auto-generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @EqualsAndHashCode.Include
    private Long id;

    /** The experiment this variable belongs to. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "experiment_id", nullable = false)
    @ToString.Exclude
    private Experiment experiment;

    /**
     * Reference to a {@link VariableType} defining this variable's metadata.
     * Every variable must belong to a type.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "variable_type_id", nullable = false)
    @ToString.Exclude
    private VariableType variableType;

    /** Timestamp of row creation, managed by Hibernate. */
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** All measured values of this variable across trials. */
    @OneToMany(mappedBy = "variable", cascade = CascadeType.ALL, orphanRemoval = true)
    @Builder.Default
    private List<TrialValue> values = new ArrayList<>();
}
