package it.deltascientia.model;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;

/**
 * Defines a measurable variable within an {@link Experiment}.
 * Variables may reference a shared {@link VariableType} for
 * cross-experiment comparability, or define standalone properties.
 */
@Entity
@Table(name = "variable")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class Variable {

    /** Unique identifier, auto-generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @EqualsAndHashCode.Include
    private Long id;

    /** The experiment this variable belongs to. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "experiment_id", nullable = false)
    @ToString.Exclude
    private Experiment experiment;

    /**
     * Optional reference to a catalog {@link VariableType}.
     * Null when the variable is fully custom without a canonical type.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "variable_type_id")
    @ToString.Exclude
    private VariableType variableType;

    /** Human-readable variable name. Must not be blank. */
    @Column(nullable = false, length = 255)
    private String name;

    /** Unit of measurement (e.g. "°C", "pH", "mg/mL"). */
    @Column(name = "unit_of_measure", length = 100)
    private String unitOfMeasure;

    /** Declared data type for value categorisation (e.g. "NUMERIC", "TEXT"). */
    @Column(name = "data_type", length = 50)
    private String dataType;

    /** Optional description of the variable's purpose. */
    @Column(length = 500)
    private String description;

    /** Timestamp of row creation, managed by Hibernate. */
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** All measured values of this variable across trials. */
    @OneToMany(mappedBy = "variable", cascade = CascadeType.ALL, orphanRemoval = true)
    @Builder.Default
    private List<TrialValue> values = new ArrayList<>();
}
